// Auto-generated by scripts/import-photos.ts — do not edit by hand.
import type { StaticImageData } from "next/image";

import type { PhotoExif } from "@/lib/types";

import p001 from "@public/images/photography/001.webp";
import p002 from "@public/images/photography/002.webp";
import p003 from "@public/images/photography/003.webp";
import p004 from "@public/images/photography/004.webp";
import p005 from "@public/images/photography/005.webp";
import p006 from "@public/images/photography/006.webp";
import p007 from "@public/images/photography/007.webp";
import p008 from "@public/images/photography/008.webp";
import p009 from "@public/images/photography/009.webp";
import p010 from "@public/images/photography/010.webp";
import p011 from "@public/images/photography/011.webp";
import p012 from "@public/images/photography/012.webp";
import p013 from "@public/images/photography/013.webp";
import p014 from "@public/images/photography/014.webp";
import p015 from "@public/images/photography/015.webp";
import p016 from "@public/images/photography/016.webp";
import p017 from "@public/images/photography/017.webp";
import p018 from "@public/images/photography/018.webp";
import p019 from "@public/images/photography/019.webp";
import p020 from "@public/images/photography/020.webp";
import p021 from "@public/images/photography/021.webp";
import p022 from "@public/images/photography/022.webp";
import p023 from "@public/images/photography/023.webp";
import p024 from "@public/images/photography/024.webp";
import p025 from "@public/images/photography/025.webp";
import p026 from "@public/images/photography/026.webp";
import p027 from "@public/images/photography/027.webp";
import p028 from "@public/images/photography/028.webp";
import p029 from "@public/images/photography/029.webp";
import p030 from "@public/images/photography/030.webp";
import p031 from "@public/images/photography/031.webp";
import p032 from "@public/images/photography/032.webp";
import p033 from "@public/images/photography/033.webp";
import p034 from "@public/images/photography/034.webp";
import p035 from "@public/images/photography/035.webp";
import p036 from "@public/images/photography/036.webp";
import p037 from "@public/images/photography/037.webp";
import p038 from "@public/images/photography/038.webp";
import p039 from "@public/images/photography/039.webp";
import p040 from "@public/images/photography/040.webp";
import p041 from "@public/images/photography/041.webp";
import p042 from "@public/images/photography/042.webp";
import p043 from "@public/images/photography/043.webp";
import p044 from "@public/images/photography/044.webp";
import p045 from "@public/images/photography/045.webp";
import p046 from "@public/images/photography/046.webp";
import p047 from "@public/images/photography/047.webp";
import p048 from "@public/images/photography/048.webp";
import p049 from "@public/images/photography/049.webp";
import p050 from "@public/images/photography/050.webp";
import p051 from "@public/images/photography/051.webp";
import p052 from "@public/images/photography/052.webp";
import p053 from "@public/images/photography/053.webp";
import p054 from "@public/images/photography/054.webp";
import p055 from "@public/images/photography/055.webp";
import p056 from "@public/images/photography/056.webp";
import p057 from "@public/images/photography/057.webp";
import p058 from "@public/images/photography/058.webp";
import p059 from "@public/images/photography/059.webp";
import p060 from "@public/images/photography/060.webp";
import p061 from "@public/images/photography/061.webp";
import p062 from "@public/images/photography/062.webp";
import p063 from "@public/images/photography/063.webp";
import p064 from "@public/images/photography/064.webp";
import p065 from "@public/images/photography/065.webp";
import p066 from "@public/images/photography/066.webp";
import p067 from "@public/images/photography/067.webp";
import p068 from "@public/images/photography/068.webp";
import p069 from "@public/images/photography/069.webp";
import p070 from "@public/images/photography/070.webp";
import p071 from "@public/images/photography/071.webp";
import p072 from "@public/images/photography/072.webp";
import p073 from "@public/images/photography/073.webp";
import p074 from "@public/images/photography/074.webp";
import p075 from "@public/images/photography/075.webp";
import p076 from "@public/images/photography/076.webp";
import p077 from "@public/images/photography/077.webp";
import p078 from "@public/images/photography/078.webp";
import p079 from "@public/images/photography/079.webp";
import p080 from "@public/images/photography/080.webp";
import p081 from "@public/images/photography/081.webp";
import p082 from "@public/images/photography/082.webp";
import p083 from "@public/images/photography/083.webp";
import p084 from "@public/images/photography/084.webp";
import p085 from "@public/images/photography/085.webp";
import p086 from "@public/images/photography/086.webp";
import p087 from "@public/images/photography/087.webp";
import p088 from "@public/images/photography/088.webp";
import p089 from "@public/images/photography/089.webp";
import p090 from "@public/images/photography/090.webp";
import p091 from "@public/images/photography/091.webp";
import p092 from "@public/images/photography/092.webp";
import p093 from "@public/images/photography/093.webp";
import p094 from "@public/images/photography/094.webp";
import p095 from "@public/images/photography/095.webp";
import p096 from "@public/images/photography/096.webp";
import p097 from "@public/images/photography/097.webp";
import p098 from "@public/images/photography/098.webp";
import p099 from "@public/images/photography/099.webp";
import p100 from "@public/images/photography/100.webp";
import p101 from "@public/images/photography/101.webp";
import p102 from "@public/images/photography/102.webp";
import p103 from "@public/images/photography/103.webp";
import p104 from "@public/images/photography/104.webp";
import p105 from "@public/images/photography/105.webp";
import p106 from "@public/images/photography/106.webp";
import p107 from "@public/images/photography/107.webp";
import p108 from "@public/images/photography/108.webp";
import p109 from "@public/images/photography/109.webp";
import p110 from "@public/images/photography/110.webp";
import p111 from "@public/images/photography/111.webp";
import p112 from "@public/images/photography/112.webp";
import p113 from "@public/images/photography/113.webp";
import p114 from "@public/images/photography/114.webp";
import p115 from "@public/images/photography/115.webp";
import p116 from "@public/images/photography/116.webp";
import p117 from "@public/images/photography/117.webp";
import p118 from "@public/images/photography/118.webp";
import p119 from "@public/images/photography/119.webp";
import p120 from "@public/images/photography/120.webp";
import p121 from "@public/images/photography/121.webp";
import p122 from "@public/images/photography/122.webp";
import p123 from "@public/images/photography/123.webp";
import p124 from "@public/images/photography/124.webp";
import p125 from "@public/images/photography/125.webp";
import p126 from "@public/images/photography/126.webp";
import p127 from "@public/images/photography/127.webp";
import p128 from "@public/images/photography/128.webp";
import p129 from "@public/images/photography/129.webp";
import p130 from "@public/images/photography/130.webp";
import p131 from "@public/images/photography/131.webp";
import p132 from "@public/images/photography/132.webp";
import p133 from "@public/images/photography/133.webp";

export interface Photo {
  image: StaticImageData;
  exif?: PhotoExif;
}

export const photos: Photo[] = [
  { image: p001 },
  {
    image: p002,
    exif: {
      camera: "DJI FC7203",
      focalLength: "24mm",
      aperture: "f/2.8",
      shutter: "1/640s",
      iso: "ISO 100",
      date: "Oct 2020",
    },
  },
  { image: p003 },
  { image: p004 },
  { image: p005 },
  {
    image: p006,
    exif: { camera: "Apple iPhone 6", focalLength: "4mm", date: "Jul 2019" },
  },
  {
    image: p007,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/15s",
      iso: "ISO 1250",
      date: "Mar 2023",
    },
  },
  {
    image: p008,
    exif: {
      camera: "Canon EOS Rebel T7",
      focalLength: "55mm",
      aperture: "f/11",
      shutter: "1/250s",
      iso: "ISO 200",
      date: "Mar 2023",
    },
  },
  { image: p009 },
  {
    image: p010,
    exif: {
      camera: "DJI FC7203",
      focalLength: "24mm",
      aperture: "f/2.8",
      shutter: "1/400s",
      iso: "ISO 100",
      date: "Oct 2021",
    },
  },
  {
    image: p011,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "210mm",
      aperture: "f/8",
      shutter: "1/500s",
      iso: "ISO 320",
      date: "Feb 2022",
    },
  },
  {
    image: p012,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "170mm",
      aperture: "f/9",
      shutter: "1/500s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p013,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "21mm",
      aperture: "f/8",
      shutter: "1/160s",
      iso: "ISO 400",
      date: "Jul 2022",
    },
  },
  {
    image: p014,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "300mm",
      aperture: "f/5.6",
      shutter: "1/200s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p015,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "170mm",
      aperture: "f/9",
      shutter: "1/500s",
      iso: "ISO 400",
      date: "Aug 2022",
    },
  },
  {
    image: p016,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "180mm",
      aperture: "f/10",
      shutter: "1/200s",
      iso: "ISO 400",
      date: "Jan 2022",
    },
  },
  {
    image: p017,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "55mm",
      aperture: "f/7.1",
      shutter: "1/125s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p018,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "35mm",
      aperture: "f/8",
      shutter: "1/100s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p019,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "95mm",
      aperture: "f/5",
      shutter: "1/125s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p020,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "300mm",
      aperture: "f/5.6",
      shutter: "1/125s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p021,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "250mm",
      aperture: "f/5.6",
      shutter: "1/250s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p022,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "80mm",
      aperture: "f/7.1",
      shutter: "1/320s",
      iso: "ISO 400",
      date: "Jan 2022",
    },
  },
  {
    image: p023,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "85mm",
      aperture: "f/9",
      shutter: "1/200s",
      iso: "ISO 400",
      date: "Jan 2022",
    },
  },
  {
    image: p024,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "46mm",
      aperture: "f/14",
      shutter: "1/200s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p025,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "46mm",
      aperture: "f/22",
      shutter: "1/500s",
      iso: "ISO 250",
      date: "Feb 2022",
    },
  },
  {
    image: p026,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "50mm",
      aperture: "f/10",
      shutter: "1/160s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p027,
    exif: {
      camera: "Apple iPhone 6s",
      focalLength: "29mm",
      aperture: "f/2.2",
      shutter: "1/1282s",
      iso: "ISO 25",
      date: "Sep 2020",
    },
  },
  {
    image: p028,
    exif: {
      camera: "Apple iPhone 6",
      focalLength: "29mm",
      aperture: "f/2.2",
      shutter: "1/30s",
      iso: "ISO 160",
      date: "Aug 2019",
    },
  },
  {
    image: p029,
    exif: {
      camera: "Canon EOS DIGITAL REBEL XTi",
      focalLength: "210mm",
      aperture: "f/7.1",
      shutter: "1/500s",
      iso: "ISO 400",
      date: "Feb 2022",
    },
  },
  {
    image: p030,
    exif: {
      camera: "Canon EOS 7D",
      focalLength: "24mm",
      aperture: "f/9",
      shutter: "1/320s",
      iso: "ISO 100",
      date: "Jun 2023",
    },
  },
  {
    image: p031,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/10753s",
      iso: "ISO 32",
      date: "Aug 2022",
    },
  },
  {
    image: p032,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/97s",
      iso: "ISO 125",
      date: "Aug 2022",
    },
  },
  {
    image: p033,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "Aug 2022",
    },
  },
  {
    image: p034,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 50",
      date: "Sep 2022",
    },
  },
  {
    image: p035,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/40s",
      iso: "ISO 500",
      date: "Feb 2023",
    },
  },
  {
    image: p036,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 50",
      date: "Feb 2023",
    },
  },
  {
    image: p037,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 64",
      date: "Feb 2023",
    },
  },
  {
    image: p038,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Feb 2023",
    },
  },
  {
    image: p039,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Feb 2023",
    },
  },
  {
    image: p040,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Feb 2023",
    },
  },
  {
    image: p041,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Feb 2023",
    },
  },
  {
    image: p042,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Feb 2023",
    },
  },
  {
    image: p043,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 64",
      date: "Mar 2023",
    },
  },
  {
    image: p044,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/6897s",
      iso: "ISO 50",
      date: "Apr 2023",
    },
  },
  {
    image: p045,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/600s",
      iso: "ISO 32",
      date: "Apr 2023",
    },
  },
  {
    image: p046,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/363s",
      iso: "ISO 32",
      date: "Jun 2023",
    },
  },
  {
    image: p047,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/381s",
      iso: "ISO 32",
      date: "Jun 2023",
    },
  },
  {
    image: p048,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/4132s",
      iso: "ISO 32",
      date: "Jul 2023",
    },
  },
  {
    image: p049,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/3401s",
      iso: "ISO 32",
      date: "Jul 2023",
    },
  },
  {
    image: p050,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/988s",
      iso: "ISO 32",
      date: "Jul 2023",
    },
  },
  {
    image: p051,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/75s",
      iso: "ISO 125",
      date: "Sep 2023",
    },
  },
  {
    image: p052,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/525s",
      iso: "ISO 32",
      date: "Oct 2023",
    },
  },
  {
    image: p053,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Oct 2023",
    },
  },
  {
    image: p054,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "Oct 2023",
    },
  },
  {
    image: p055,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/211s",
      iso: "ISO 32",
      date: "Oct 2023",
    },
  },
  {
    image: p056,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Dec 2023",
    },
  },
  {
    image: p057,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 100",
      date: "Dec 2023",
    },
  },
  {
    image: p058,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/60s",
      iso: "ISO 160",
      date: "Dec 2023",
    },
  },
  {
    image: p059,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 100",
      date: "Dec 2023",
    },
  },
  {
    image: p060,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/350s",
      iso: "ISO 32",
      date: "Dec 2023",
    },
  },
  {
    image: p061,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Dec 2023",
    },
  },
  {
    image: p062,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Dec 2023",
    },
  },
  {
    image: p063,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 64",
      date: "Dec 2023",
    },
  },
  {
    image: p064,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/238s",
      iso: "ISO 32",
      date: "Dec 2023",
    },
  },
  {
    image: p065,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Dec 2023",
    },
  },
  {
    image: p066,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/127s",
      iso: "ISO 32",
      date: "Jan 2024",
    },
  },
  {
    image: p067,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/208s",
      iso: "ISO 32",
      date: "Feb 2024",
    },
  },
  {
    image: p068,
    exif: {
      camera: "Canon EOS 7D",
      focalLength: "150mm",
      aperture: "f/5",
      shutter: "1/320s",
      iso: "ISO 500",
      date: "Apr 2024",
    },
  },
  {
    image: p069,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Apr 2024",
    },
  },
  {
    image: p070,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "May 2024",
    },
  },
  {
    image: p071,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/252s",
      iso: "ISO 32",
      date: "May 2024",
    },
  },
  {
    image: p072,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1033s",
      iso: "ISO 32",
      date: "Jul 2021",
    },
  },
  {
    image: p073,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 50",
      date: "Aug 2021",
    },
  },
  {
    image: p074,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/558s",
      iso: "ISO 32",
      date: "Aug 2021",
    },
  },
  {
    image: p075,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1147s",
      iso: "ISO 32",
      date: "Aug 2021",
    },
  },
  {
    image: p076,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/988s",
      iso: "ISO 32",
      date: "Aug 2021",
    },
  },
  {
    image: p077,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 32",
      date: "Aug 2021",
    },
  },
  {
    image: p078,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 32",
      date: "Aug 2021",
    },
  },
  {
    image: p079,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/296s",
      iso: "ISO 32",
      date: "Aug 2021",
    },
  },
  {
    image: p080,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Oct 2021",
    },
  },
  {
    image: p081,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "14mm",
      aperture: "f/2.4",
      shutter: "1/417s",
      iso: "ISO 25",
      date: "Oct 2021",
    },
  },
  {
    image: p082,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "Oct 2021",
    },
  },
  {
    image: p083,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/479s",
      iso: "ISO 32",
      date: "Oct 2021",
    },
  },
  {
    image: p084,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/694s",
      iso: "ISO 32",
      date: "Oct 2021",
    },
  },
  {
    image: p085,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "Jan 2022",
    },
  },
  {
    image: p086,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "Feb 2022",
    },
  },
  {
    image: p087,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/2020s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p088,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/2020s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p089,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1024s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p090,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1171s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p091,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "27mm",
      aperture: "f/1.6",
      shutter: "1/1024s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p092,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/292s",
      iso: "ISO 40",
      date: "Feb 2022",
    },
  },
  {
    image: p093,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1618s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p094,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/3300s",
      iso: "ISO 50",
      date: "Feb 2022",
    },
  },
  {
    image: p095,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "32mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 100",
      date: "Feb 2022",
    },
  },
  {
    image: p096,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/124s",
      iso: "ISO 32",
      date: "Feb 2022",
    },
  },
  {
    image: p097,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "Jun 2022",
    },
  },
  {
    image: p098,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/855s",
      iso: "ISO 50",
      date: "Jun 2022",
    },
  },
  {
    image: p099,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/30s",
      iso: "ISO 500",
      date: "Jul 2022",
    },
  },
  {
    image: p100,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "28mm",
      aperture: "f/2.2",
      shutter: "1/99s",
      iso: "ISO 125",
      date: "Jun 2024",
    },
  },
  {
    image: p101,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/2053s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p102,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/7299s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p103,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1261s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p104,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "57mm",
      aperture: "f/1.6",
      shutter: "1/7299s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p105,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "14mm",
      aperture: "f/2.2",
      shutter: "1/236s",
      iso: "ISO 40",
      date: "Jun 2024",
    },
  },
  {
    image: p106,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/99s",
      iso: "ISO 100",
      date: "Jul 2024",
    },
  },
  {
    image: p107,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/198s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p108,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 64",
      date: "Jul 2022",
    },
  },
  {
    image: p109,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/932s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p110,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/1511s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p111,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/888s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p112,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/924s",
      iso: "ISO 32",
      date: "Jul 2022",
    },
  },
  {
    image: p113,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/1.8",
      shutter: "1/822s",
      iso: "ISO 80",
      date: "Jul 2024",
    },
  },
  {
    image: p114,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "53mm",
      aperture: "f/1.8",
      shutter: "1/171s",
      iso: "ISO 64",
      date: "Jul 2024",
    },
  },
  {
    image: p115,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/99s",
      iso: "ISO 125",
      date: "Jul 2024",
    },
  },
  {
    image: p116,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/93s",
      iso: "ISO 320",
      date: "Jul 2024",
    },
  },
  {
    image: p117,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/94s",
      iso: "ISO 320",
      date: "Jul 2024",
    },
  },
  {
    image: p118,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/99s",
      iso: "ISO 160",
      date: "Jul 2024",
    },
  },
  {
    image: p119,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/60s",
      iso: "ISO 500",
      date: "Jul 2024",
    },
  },
  {
    image: p120,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/99s",
      iso: "ISO 250",
      date: "Jul 2024",
    },
  },
  {
    image: p121,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 64",
      date: "Aug 2022",
    },
  },
  {
    image: p122,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 125",
      date: "Aug 2022",
    },
  },
  {
    image: p123,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "29mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 50",
      date: "Aug 2022",
    },
  },
  {
    image: p124,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "29mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Aug 2022",
    },
  },
  {
    image: p125,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 80",
      date: "Aug 2022",
    },
  },
  {
    image: p126,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/1.8",
      shutter: "1/147s",
      iso: "ISO 64",
      date: "Aug 2024",
    },
  },
  {
    image: p127,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/1.8",
      shutter: "1/396s",
      iso: "ISO 200",
      date: "Aug 2024",
    },
  },
  {
    image: p128,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/1.8",
      shutter: "1/1002s",
      iso: "ISO 160",
      date: "Aug 2024",
    },
  },
  {
    image: p129,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/932s",
      iso: "ISO 50",
      date: "Aug 2024",
    },
  },
  {
    image: p130,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/980s",
      iso: "ISO 40",
      date: "Aug 2024",
    },
  },
  {
    image: p131,
    exif: {
      camera: "Apple iPhone 15 Pro",
      focalLength: "24mm",
      aperture: "f/2.2",
      shutter: "1/186s",
      iso: "ISO 40",
      date: "Aug 2024",
    },
  },
  {
    image: p132,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "82mm",
      aperture: "f/1.6",
      shutter: "1/315s",
      iso: "ISO 32",
      date: "May 2021",
    },
  },
  {
    image: p133,
    exif: {
      camera: "Apple iPhone 12 mini",
      focalLength: "26mm",
      aperture: "f/1.6",
      shutter: "1/121s",
      iso: "ISO 40",
      date: "May 2021",
    },
  },
];
