/**
 * Photo import pipeline for the /photos page. Run with:
 *
 *   bun scripts/import-photos.ts [source-dir]
 *
 * With a source-dir of original JPGs (named NNN.jpg), each is converted to a
 * metadata-stripped WebP in public/images/photography/ and its EXIF (minus
 * GPS) is recorded in src/lib/photo-exif.json. Without a source-dir, only the
 * manifest is regenerated from the existing WebPs and JSON.
 *
 * Requires ImageMagick (`magick`).
 */
import { spawnSync } from "child_process";
import { readdirSync, existsSync, readFileSync, writeFileSync } from "fs";
import { basename, join } from "path";

import type { PhotoExif } from "../src/lib/types";

const ROOT = join(new URL(".", import.meta.url).pathname, "..");
const PHOTO_DIR = join(ROOT, "public/images/photography");
const EXIF_JSON = join(ROOT, "src/lib/photo-exif.json");
const MANIFEST = join(ROOT, "src/lib/photos.ts");

const run = (cmd: string[]): string => {
  const proc = spawnSync(cmd[0], cmd.slice(1), { encoding: "utf-8" });
  if (proc.status !== 0) {
    throw new Error(`${cmd[0]} failed: ${proc.stderr}`);
  }
  return proc.stdout;
};

const rational = (value?: string): number | null => {
  if (!value) return null;
  const [num, den] = value.split("/").map(Number);
  if (Number.isNaN(num)) return null;
  const result = den ? num / den : num;
  return Number.isFinite(result) && result > 0 ? result : null;
};

const readExif = (file: string): PhotoExif | undefined => {
  const raw = run(["magick", "identify", "-format", "%[EXIF:*]", file]);
  const tags: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    const eq = line.indexOf("=");
    if (eq > 0) tags[line.slice(5, eq)] = line.slice(eq + 1);
  }

  const exif: PhotoExif = {};

  const make = tags["Make"]?.trim();
  const model = tags["Model"]?.trim();
  if (model) {
    exif.camera =
      make && !model.toLowerCase().startsWith(make.toLowerCase())
        ? `${make} ${model}`
        : model;
  }

  const focal35 = rational(tags["FocalLengthIn35mmFilm"]);
  const focal = focal35 ?? rational(tags["FocalLength"]);
  if (focal) exif.focalLength = `${Math.round(focal)}mm`;

  const fNumber = rational(tags["FNumber"]);
  if (fNumber) exif.aperture = `f/${parseFloat(fNumber.toFixed(1))}`;

  const exposure = rational(tags["ExposureTime"]);
  if (exposure) {
    exif.shutter =
      exposure >= 1
        ? `${parseFloat(exposure.toFixed(1))}s`
        : `1/${Math.round(1 / exposure)}s`;
  }

  const iso = tags["PhotographicSensitivity"] ?? tags["ISOSpeedRatings"];
  if (iso && Number(iso) > 0) exif.iso = `ISO ${iso}`;

  const date = tags["DateTimeOriginal"] ?? tags["DateTime"];
  if (date) {
    const parsed = new Date(date.replace(/^(\d{4}):(\d{2}):/, "$1-$2-"));
    if (!Number.isNaN(parsed.getTime())) {
      exif.date = parsed.toLocaleDateString("en-US", {
        month: "short",
        year: "numeric",
      });
    }
  }

  return Object.keys(exif).length > 0 ? exif : undefined;
};

const importOriginals = (sourceDir: string): Record<string, PhotoExif> => {
  const exifByName: Record<string, PhotoExif> = existsSync(EXIF_JSON)
    ? JSON.parse(readFileSync(EXIF_JSON, "utf-8"))
    : {};

  const originals = readdirSync(sourceDir)
    .filter((f) => /\.(jpe?g|png|heic)$/i.test(f))
    .sort();

  for (const file of originals) {
    const name = basename(file).replace(/\.[^.]+$/, "");
    const source = join(sourceDir, file);
    run([
      "magick",
      source,
      "-auto-orient",
      "-resize",
      "1600x1600>",
      "-strip",
      "-quality",
      "80",
      join(PHOTO_DIR, `${name}.webp`),
    ]);
    const exif = readExif(source);
    if (exif) exifByName[name] = exif;
    console.warn(`imported ${file}`);
  }

  writeFileSync(EXIF_JSON, JSON.stringify(exifByName, null, 2) + "\n");
  return exifByName;
};

const writeManifest = (exifByName: Record<string, PhotoExif>) => {
  const names = readdirSync(PHOTO_DIR)
    .filter((f) => f.endsWith(".webp"))
    .map((f) => basename(f, ".webp"))
    .sort();

  const lines = [
    "// Auto-generated by scripts/import-photos.ts — do not edit by hand.",
    'import type { StaticImageData } from "next/image";',
    "",
    'import type { PhotoExif } from "@/lib/types";',
    "",
    ...names.map(
      (n) => `import p${n} from "@public/images/photography/${n}.webp";`
    ),
    "",
    "export interface Photo {",
    "  image: StaticImageData;",
    "  exif?: PhotoExif;",
    "}",
    "",
    "export const photos: Photo[] = [",
    ...names.map((n) => {
      const exif = exifByName[n];
      return exif
        ? `  { image: p${n}, exif: ${JSON.stringify(exif)} },`
        : `  { image: p${n} },`;
    }),
    "];",
    "",
  ];
  writeFileSync(MANIFEST, lines.join("\n"));
  console.warn(`wrote ${MANIFEST} (${names.length} photos)`);
};

const sourceDir = process.argv[2];
const exifByName = sourceDir
  ? importOriginals(sourceDir)
  : existsSync(EXIF_JSON)
    ? JSON.parse(readFileSync(EXIF_JSON, "utf-8"))
    : {};
writeManifest(exifByName);
