name: Tangle

on:
  push: {}
  workflow_dispatch: {}

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
      - uses: gwennlbh/to-tangled@v0.3
        with:
          repo: jaspermayone.com/website
          ssh-key: ${{ secrets.TANGLED_KEY }}

